[package]
name = "scanner-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sane-scan = { git = "https://github.com/sunsided/sane-scan", rev = "0fc9a72" }
