---
name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsane libsane-dev
      - name: Run Tests
        run: cargo test
